### ISSUE TITLE
Uncaught Error in task "bundle" when bower_components isn't present

### ISSUE THREAD

**Issue by fabdrol** [randylien/generator-react-gulp-browserify#15]
I'm getting an uncaught error in the "bundle" task when `bower_components` isn't present:

```
Uncaught error:
 Uncaught, unspecified "error" event.
```

**Comment by patrickdmccarthy** [comment]
Bower install still does not install Bower packages, so that when I clone my own project I get errors because jQuery and bootstrap-sass are found.
