### ISSUE TITLE
Does not work with Sass option unselected

### ISSUE THREAD

**Issue by olalonde** [randylien/generator-react-gulp-browserify#17]
The generator has multiple bugs when the Sass option is not selected. I suggest this option should be removed or fixed.

In addition, the following needs to be installed manually:

```
npm install --save-dev gulp-ruby-sass gulp-useref
```

Also, there is a bug in the `bundle` task. This fix seems to work:

```javascript
gulp.task('bundle', ['styles', 'scripts', 'bower'], function(){
    var useref = $.useref;
    var assets = useref.assets();
    return gulp.src('./app/*.html')
      .pipe(assets)
      .pipe(assets.restore())
      .pipe(useref())
      .pipe(gulp.dest('dist'));
});
```

Also, `bower install` fails if no project name is specified when running the generator. Probably the script should use the current folder name, use a default name like `app` or refuse to generate if no name is provided.

Well, I think I finally solved all the bugs I got.

**Comment by olalonde** [comment]
Oh one more thing, I'm getting this in the console:

```javascript
 Warning: React.renderComponent will be deprecated in a future version. Use React.render instead.
app.js:19132 Uncaught Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.
```

This was fixed by adding the following in my index.html:

```html
        <div id="app"></div>
```

**Comment by olalonde** [comment]
Hmmm seems bootstrap was not included. I re-ran the generator with bootstrap and it seems to work now.

**Comment by olalonde** [comment]
Another thing, the build and watch tasks do not copy favicon.ico and robots.txt to dist/. I added the following task:

```javascript
// Robots.txt and favicon.ico
gulp.task('extras', function () {
    return gulp.src(['app/*.txt', 'app/*.ico'])
        .pipe(gulp.dest('dist/'))
        .pipe($.size());
});
```

**Comment by randylien** [comment]
@olalonde thanks for your hard work.
I will fix those issues in the next update.

**Comment by randylien** [comment]
@olalonde please check latest commit.
