### ISSUE TITLE
Problems right after initialisation

### ISSUE THREAD

**Issue by optikfluffel** [randylien/generator-react-gulp-browserify#24]
Hi @randylien,

first of all thanks for this generator. But I have some problems getting it all up and running. I have Node (`v0.10.36`), Bower (`1.3.12`) and Sass (`3.4.12`) installed, ran through the configuration process (the only thing I deselected was jade support) and then tried to run:

```shell
gulp clean && gulp build && gulp jest
```

* First problem is, that the build task actually never quits. (already discussed in #20)
* If I kill it with `ctrl + c` and run `gulp jest` manually the test fails with:

```
Error: /Users/optikfluffel/my_webapp/app/scripts/ui/__tests__/Timer-test.js: Cannot find module '../Timer' from '/Users/optikfluffel/my_webapp/app/scripts/ui/__tests__/Timer-test.js'
```

also in my built `app.js` there is strange stuff like

```javascript
Timer = require("./ui/Timer.coffee");
```

going on. Do you have a cloud what's wrong on my side here?

Thanks in advance, optikfluffel

**Comment by marclar** [comment]
Had the same problem -- it seems that `/node_modules/gulp-jest/preprocessor.js` expects tests to have `*.jsx` file extensions. 

I changed `Timer-test.js` to `Timer-test.jsx`. It doesn't fail anymore, but it also says `0 test passed (0 total)`

**Comment by cyrandy** [comment]
+1 Same problem.

**Comment by randylien** [comment]
Hi all,
Thanks for your feedback and I found the root cause.
I am working on it now :)

**Comment by randylien** [comment]
Hi @optikfluffel ,
About the first question, please try 0.21. I refactor build task flow.

**Comment by randylien** [comment]
Hi @cyrandy @marclar,
Please check the new `npm task` to run jest-cli.
