### ISSUE TITLE
Cannot GET / issue

### ISSUE THREAD

**Issue by tnedich** [randylien/generator-react-gulp-browserify#25]
Everything goes ok, but when I start my project with gulp watch and go to localhost:9000 I get  only:

> Cannot GET /

**Comment by fionnbharra** [comment]
I have the same issue

**Comment by fionnbharra** [comment]
ignore my last comment, my error was caused as I had two gulp processes running on the same port

**Comment by tnedich** [comment]
Now it just work, must be something strange on my machine.
