### ISSUE TITLE
React.renderComponent is not a function

### ISSUE THREAD

**Issue by leszekhanusz** [randylien/generator-react-gulp-browserify#29]
Running gulp watch for the first time, the following text appears in the console (app.js: 61)

    TypeError: React.renderComponent is not a function	
    React.renderComponent(React.createElement(TodoApp, null), mountNode);

Apparently `renderComponent` is renamed `render` in v0.12
https://facebook.github.io/react/blog/2014/10/28/react-v0.12.html

**Comment by randylien** [comment]
Thanks for your report.
I forget to update app.coffee template.

**Comment by randylien** [comment]
Please try the new version 0.23.
