### ISSUE TITLE
Not right use of watchify

### ISSUE THREAD

**Issue by bichotll** [randylien/generator-react-gulp-browserify#35]
I've noticed that the rebuild was sooo slow. I just figured out the wrong use of watchify.
You should use watchify for js files and gulp.watch for the others.
What you are doing in your code is begin a watchify process everytime there is a change on the code.

I'm just trying to solve this problem properly. If I solve it (I'm done but not for the reload), I'll let you know.

Cheers

**Comment by bichotll** [comment]
Here the working prototype ;)

https://github.com/bichotll/generator-react-gulp-browserify

Feel free to merge!

**Comment by randylien** [comment]
Hi @bichotll ,
Thanks for your help and I just fix this issue according to your prototype.
