### ISSUE TITLE
Can't enable CORS 

### ISSUE THREAD

**Issue by 5punk** [randylien/generator-react-gulp-browserify#40]
I tried a whole bunch of different ways to enable CORS as I was getting " No 'Access-Control-Allow-Origin' header is present on the requested resource." whenever I was trying to make an Ajax call.

I tried to enable it this way. But didn't work.

````
browserSync({
    notify: false,
    port: 3000,
    server: {
      baseDir: ['dist', 'app'],
      middleware: function (req, res, next) {
        res.setHeader('Access-Control-Allow-Origin', '*');
        next();
      }
    }
});
````

Any help please?

**Comment by randylien** [comment]
Do you make your application which is generated by this generator to allow to CORS in development stage ?

**Comment by stereokai** [comment]
@5punk ?

**Comment by codeofsumit** [comment]
@stereokai CORS needs to be enabled on the server you're sending the request to, not here in this generator / dev server.

E.g. if you want the latest tweets from twitter, twitter has to enable CORS so you can make client side requests cross domain.
If you don't have control over the server that you're making your ajax calls to, try out jsonp or move your logic server-side using node or php or something.

**Comment by randylien** [comment]
Thanks for your explanation!
