### ISSUE TITLE
gulp watch fails when build for 1st time

### ISSUE THREAD

**Issue by jma7889** [randylien/generator-react-gulp-browserify#56]
error message:
events.js:141
      throw er; // Unhandled 'error' event
      ^

**Comment by fmontes** [comment]
I fix it by changing this:
```<script src="bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js"></script>```

fot this:
```<script src="bower_components/bootstrap-sass-official/assets/javascripts/bootstrap.min.js"></script>```

**Comment by randylien** [comment]
This one is fixed. Please try it again. Thanks
